### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 45O** [wilderzone/discord-team-reset-bot#1]
So this isn't for your bot but they both use discord_client.run(config["discord_bot_token"])
so I'm curious if you'd know a fix for this, after it runs it shows "KeyError:" and the error is the token but I know they're valid tokens here is the repo file I'm talking about https://github.com/kkapuria3/Telegram-To-Discord-Forward-Bot/blob/master/discord_messager.py

**Comment by chickenbellyfin** [comment]
KeyError would usually mean that 'discord_bot_token' is not in your config file, or maybe spelled wrong. I can't really tell more without the whole error message.
